### ISSUE TITLE
Add fallbackValue arg to createQueryMiddleware

### ISSUE THREAD

**Issue by alexesDev** [4Catalyzer/farce#40]
Sometimes
```js
query = parse(location.search.slice(1));
```
ends with error and code like
```js
location.query.modal
```
throw error and I cant see a REAL error becouse...
```js
catch (e) {
  // log e ???
  query = null;
}
```
Now I'm using custom copy-past middleware with patches.

**Comment by alexesDev** [comment]
Solution...
```js
import createQueryMiddleware from 'farce/lib/createQueryMiddleware';
import queryString from 'query-string';

const queryMiddleware = createQueryMiddleware({
  parse: (search) => {
    try {
      return queryString.parse(search);
    } catch (e) {
      return {};
    }
  },
  stringify: queryString.stringify,
});
```
Thanks for the amazing lib!

**Comment by taion** [comment]
@alexesDev 

Can you share an example of the query string that was causing this problem? Supposedly the new version of query-string is a bit more lenient, and I'd like to see if it qualitatively changes behavior.

Otherwise, yeah, setting a default here is hard; there's no real way to surface anything like a catchable exception here, so I figured setting the query to `null` was the best I could do.

Definitely if you want to capture those in Raven, what you have is the approach I had in mind.

Let me know if you have any ideas for making the default behavior better.

**Comment by alexesDev** [comment]
> Can you share an example of the query string that was causing this problem?
No =( Raven catches an error and (maybe) clears it. I updated the code and if it catches an error, I'll write.

**Comment by taion** [comment]
Okay, no worries. If you catch one, it'd be great, though. I want to see how https://github.com/sindresorhus/query-string/releases/tag/v5.0.0 does, and I'd prefer to check on a real-world example, not something that I come up with.

**Comment by alexesDev** [comment]
Catched! [example](https://myfresh.ru/catalog/ryba-6/moreprodukty-94/krevetki-sukhoy-zamorozki-iz-okhotskogo-morya-2182.html?frommarket=https%3A//market.yandex.ru/api/search%3Fhid%3D%26text%3D%D0%BA%D1%83%D0%BF%D0%B8%D1%82%D1%8C+%D0%BA%D1%80%D0%B5%D0%B2%D0%B5%D1%25&ymclid=083567846164577576400050)

```
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
```

**Comment by alexesDev** [comment]
query-string@5.0.0 solved the problem. Thanks!

**Comment by taion** [comment]
Cool. I updated the dependency in [v0.2.2](https://github.com/4Catalyzer/farce/releases/tag/v0.2.2).
